version: '2.1'

services:

  <%= projectDirectory %>:
    build:
      context: .
      dockerfile: gradle/Dockerfile
    volumes: ['<%= projectDirectory %>-data:/home/appuser']
    ports: ['8080:8080']
    restart: unless-stopped
    # container limit: 200Mb (200 * 1024 * 1024)
    mem_limit: 209715200
    networks:
      public-network:
        aliases:
        - app

volumes:
  <%= projectDirectory %>-data:

networks:
  public-network:
    driver: bridge
