version: '2.2'

services:

  <%= projectDirectory %>:
    build:
      context: .
      dockerfile: gradle/Dockerfile
    ports:
    - '5005:5005'
    - '8080:8080'
    networks: [backing-services]

networks:
  backing-services:
    driver: bridge
