version: "2.1"

services:

  maven-<%= projectDirectory %>-app:
    build:
      context: .
      dockerfile: .mvn/Dockerfile
    volumes: ["maven-<%= projectDirectory %>-app-data:/home/app"]
    ports:
    - "5005:5005"
    - "8080:8080"
    - "9990:9990"
    networks: [backing-services]
    #mem_limit: 786432000 # container limit: 700Mb (700 * 1024 * 1024)

volumes:
  maven-<%= projectDirectory %>-app-data: {}

networks:
  backing-services:
    driver: bridge
