service:
- docker

env:
  global:
  - TERM=dumb

language: java
jdk: oraclejdk8

apt:
  update: true
  packages:
  - bash
  - unzip
  - curl
  - jq
  - libxml2-utils
  - docker-ce
  - python-pip

install: true
before_script:
- sudo pip install docker-compose httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)

script:
- bash gradlew >/dev/null
- java -jar ./build/libs/*-all.jar
#
- bash gradlew clean installDist >/dev/null
- bash ./build/install/<%= projectDirectory %>/bin/<%= projectDirectory %>
#
- bash gradlew clean distZip >/dev/null
- unzip -o ./build/distributions/<%= projectDirectory %>-0.0.1.zip -d /tmp
- bash /tmp/<%= projectDirectory %>-0.0.1/bin/<%= projectDirectory %>
#
- bash gradlew clean build composeUp
- bash gradlew composeDown
#
- bash mvnw clean package >/dev/null
- java -jar target/*-all.jar
#
- bash mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:up
- bash mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:down

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
